
name: AWS-SDK

on:

  #push:
  #  branches: [ main ]

  workflow_dispatch:


jobs:

  storage:

    runs-on: ubuntu-latest

    environment: storage

    #permissions:
    #  id-token: write
    #  contents: read

    steps:

    #- name: Checkout Code
    #  uses: actions/checkout@v2

    - name: Configure Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: us-west-2
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        #role-external-id: ${{ secrets.AWS_ROLE_EXTERNAL_ID }}
        #role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
        #mask-aws-account-id: true
        #role-duration-seconds: 300
        #role-session-name: GitHubActions
        #role-skip-session-tagging: true

    - name: Run a multi-line script
      run: |
        env > workflow
        now=$(date -Iseconds)
        aws s3 sync . s3://net-gurumojo-ci/$now

