
name: CI-CD

env:
  AWS_REGION: us-west-2
  COMMIT: ${{ github.sha }}
  NODE_ENV: production
  NODE_VERSION: 14.x
  S3_PATH: ${{ secrets.STORAGE_BUCKET }}/${{ github.repository }}

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  integration:

    runs-on: ubuntu-latest

    environment: storage

    steps:

    - name: Checkout code updates
      uses: actions/checkout@v2

    - name: Use node ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Clone dependencies
      run: |
        set -o pipefail
        npm ci | tee -a integration.log
      env:
        NODE_ENV: 'development'

    - name: Build artifacts
      run: |
        set -o pipefail
        npm run build --if-present | tee -a integration.log

    - name: Run unit tests
      run: |
        set -o pipefail
        npm test | tee -a integration.log

    - name: Create tarball
      run: |
        rm -rf .git .github .gitignore
        tar -cvf ${{ github.repository }}-${{ github.sha }}-${{ env.NODE_VERSION }}.tar .
        rm -rf node_modules

    - name: Configure Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: ${{ env.AWS_REGION }}
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        #role-external-id: ${{ secrets.AWS_ROLE_EXTERNAL_ID }}
        #role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
        #mask-aws-account-id: true
        #role-duration-seconds: 300
        #role-session-name: GitHubActions
        #role-skip-session-tagging: true

    - name: Upload artifacts
      run: |
        aws s3 cp . \
        s3://${{ env.S3_PATH }}/${{ github.sha }} \
        --recursive --exclude "*" --include "*.log" --include "*.tar"


  acceptance:

    needs: integration

    runs-on: ubuntu-latest

    environment: storage

    steps:

    - name: Configure Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: ${{ env.AWS_REGION }}
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Download artifacts
      run: |
        set -o pipefail
        aws s3 sync \
        s3://${{ env.S3_PATH }}/${{ github.sha }} \
        . | tee -a acceptance.log

    - name: Unpack tarball
      run: tar -xf ${{ github.repository }}-${{ github.sha }}-${{ env.NODE_VERSION }}.tar

    - name: Use node ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Run acceptance scenarios
      run: |
        set -o pipefail
        npm run scenario | tee -a acceptance.log

    - name: Upload artifacts
      run: |
        aws s3 cp acceptance.log \
        s3://${{ env.S3_PATH }}/${{ github.sha }}/acceptance.log


  capacity:

    needs: integration

    runs-on: ubuntu-latest

    environment: storage

    steps:

    - name: Configure Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: ${{ env.AWS_REGION }}
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Download artifacts
      run: |
        set -o pipefail
        aws s3 sync \
        s3://${{ env.S3_PATH }}/${{ github.sha }} \
        . | tee -a acceptance.log

    - name: Unpack tarball
      run: tar -xf ${{ github.repository }}-${{ github.sha }}-${{ env.NODE_VERSION }}.tar

    - name: Use node ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Run capacity scenarios
      run: |
        set -o pipefail
        npm run capacity --if-present | tee -a capacity.log

    - name: Upload artifacts
      run: |
        aws s3 cp capacity.log \
        s3://${{ env.S3_PATH }}/${{ github.sha }}/capacity.log


  deployment:

    needs: [ acceptance, capacity ]

    runs-on: ubuntu-latest

    environment: acceptance

    steps:

    - name: Configure Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: ${{ env.AWS_REGION }}
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Download artifacts
      run: |
        set -o pipefail
        aws s3 sync \
        s3://${{ env.S3_PATH }}/${{ github.sha }} \
        . | tee -a deployment.log

    - name: Unpack tarball
      run: tar -xf ${{ github.repository }}-${{ github.sha }}-${{ env.NODE_VERSION }}.tar

    - name: Use node ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Upload artifacts
      run: |
        aws s3 cp deployment.log \
        s3://${{ env.S3_PATH }}/${{ github.sha }}/deployment.log


  release:

    needs: deployment

    runs-on: ubuntu-latest

    environment: production

    steps:

    - name: Configure Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: ${{ env.AWS_REGION }}
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Download artifacts
      run: |
        set -o pipefail
        aws s3 sync \
        s3://${{ env.S3_PATH }}/${{ github.sha }} \
        . | tee -a release.log

    - name: Unpack tarball
      run: tar -xf ${{ github.repository }}-${{ github.sha }}-${{ env.NODE_VERSION }}.tar

    - name: Use node ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Debug logging
      run: |
        cat package.json | tee -a release.log
        tree . | tee -a release.log

    - name: Upload artifacts
      run: |
        aws s3 cp release.log \
        s3://${{ env.S3_PATH }}/${{ github.sha }}/release.log

