
name: CI-CD

env:
  COMMIT: ${{ github.sha }}
  NODE_ENV: production
  NODE_VERSION: 14.x

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  integration:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout code updates
      uses: actions/checkout@v2

    - name: Use node ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Clone dependencies
      run: npm ci
      env:
        NODE_ENV: 'development'

    - name: Build artifacts
      run: npm run build --if-present

    - name: Run unit tests
      run: npm test

    - name: Create tarball
      run: |
        echo ${{ github.sha }} > version
        rm -rf .git .github .gitignore
        tar -cvf build-${{ env.NODE_VERSION }}-${{ github.sha }}.tar .

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: builds
        path: build-${{ env.NODE_VERSION }}-${{ github.sha }}.tar


  acceptance:

    needs: integration

    runs-on: ubuntu-latest

    steps:

    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        name: builds

    - name: Unpack tarball
      run: tar -xf build-${{ env.NODE_VERSION }}-${{ github.sha }}.tar

    - name: Use node ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Run acceptance scenarios
      run: npm run scenario

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: acceptance-${{ env.NODE_VERSION }}-${{ github.sha }}
        path: acceptance.log


  capacity:

    needs: integration

    runs-on: ubuntu-latest

    steps:

    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        name: builds

    - name: Unpack tarball
      run: |
        tar -xf build-${{ env.NODE_VERSION }}-${{ github.sha }}.tar
        cat version

    - name: Use node ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Run capacity scenarios
      run: npm run capacity --if-present

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: capacity-${{ env.NODE_VERSION }}-${{ github.sha }}
        path: capacity.log


  deployment:

    needs: [ acceptance, capacity ]

    runs-on: ubuntu-latest

    environment: acceptance

    steps:

    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        name: builds

    - name: Unpack tarball
      run: tar -xf build-${{ env.NODE_VERSION }}-${{ github.sha }}.tar

    - name: Use node ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'


  release:

    needs: deployment

    runs-on: ubuntu-latest

    environment: production

    steps:

    - name: Download artifacts
      uses: actions/download-artifact@v2

    - name: Debug logging
      run: tree .

